CHROME_DRIVER: "/usr/bin/chromedriver"
KINDLEGEN_LOC: "/usr/bin/kindlegen/kindlegen"
SITE_NAME : "stringprint2"

#https://www.miniwebtool.com/django-secret-key-generator/
SECRET_KEY: 'MEANT_FOR_LOCAL_USE_BUT_CHANGE_IF_CONVERTED_TO_LIVE_APP'

#https://tinypng.com/developers
TINY_PNG_KEY: ""

ORGS:
  default:
    storage_dir: /workspaces/stringprint_document_source