# Generated by Django 2.1 on 2019-03-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stringprint", "0023_auto_20180707_1114"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="access",
            name="article",
        ),
        migrations.RemoveField(
            model_name="access",
            name="secret_word",
        ),
        migrations.RemoveField(
            model_name="access",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ipaccess",
            name="access",
        ),
        migrations.RemoveField(
            model_name="secretword",
            name="article",
        ),
        migrations.RemoveField(
            model_name="article",
            name="paywall",
        ),
        migrations.RemoveField(
            model_name="article",
            name="public",
        ),
        migrations.AlterField(
            model_name="article",
            name="bottom_iframe",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="first_section_name",
            field=models.CharField(blank=True, default="start", max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf_location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="production_url",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="repo_entry",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="asset",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="asset",
            name="image_chart",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[("h", "html"), ("i", "image"), ("c", "chart")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="headerimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="headerimage",
            name="image_vertical",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="custom_css",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="fonts",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="Access",
        ),
        migrations.DeleteModel(
            name="IPAccess",
        ),
        migrations.DeleteModel(
            name="SecretWord",
        ),
    ]
