# Generated by Django 2.1 on 2020-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stringprint", "0034_asset_no_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="display_toc",
            field=models.BooleanField(default=False),
        ),
    ]
