# Generated by Django 2.1 on 2020-07-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stringprint", "0037_article_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="preprocessor",
            field=models.TextField(default=""),
        ),
    ]
