# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 09:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stringprint", "0020_auto_20170727_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="display_footnotes_at_foot",
            field=models.BooleanField(default=True),
        ),
    ]
