# Generated by Django 2.1 on 2019-05-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stringprint', '0026_auto_20190502_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='publish_dir',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='storage_dir',
        ),
    ]
