# Generated by Django 2.1 on 2020-01-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stringprint', '0033_asset_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='no_header',
            field=models.BooleanField(default=False),
        ),
    ]
