# Generated by Django 2.1 on 2020-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stringprint', '0035_article_display_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
