# Generated by Django 2.1 on 2019-05-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_tokensetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='article',
        ),
        migrations.DeleteModel(
            name='TokenSetting',
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'User Settings'},
        ),
        migrations.DeleteModel(
            name='Download',
        ),
    ]
